---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hemanth.hemanth.vit
  resources:
  - ebpffirewalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hemanth.hemanth.vit
  resources:
  - ebpffirewalls/finalizers
  verbs:
  - update
- apiGroups:
  - hemanth.hemanth.vit
  resources:
  - ebpffirewalls/status
  verbs:
  - get
  - patch
  - update
